name: easyrepro

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ matrix.nuget }}

    - name: Nuget restore
      working-directory: EasyReproDemo
      run: nuget restore EasyReproDemo.sln
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
         
    - name: build-test-assembly
      working-directory: EasyReproDemo
      run: msbuild /t:rebuild
      
    - name: Run tests
      working-directory: EasyReproDemo\obj\Debug\
      env:
        appurl: 'https://dreamingincrm.crm6.dynamics.com/Apps/uniquename/Customerservicehub'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        mfaToken: ${{ secrets.mfaToken }}
      run:  '& "$(vswhere -latest -products * -property installationPath)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" EasyReproDemo.dll /Platform:AnyCPU /Framework:.NETFramework,Version=v4.6.2'
